kind = "DojoModel"
class_hash = "0x56861f7a7224ee70e86355af6c36f58a70919d519b945bf8715f5890e876e7d"
original_class_hash = "0x56861f7a7224ee70e86355af6c36f58a70919d519b945bf8715f5890e876e7d"
abi = "manifests/sepoliadev1/base/abis/models/zkube-Mint-56f569fb.json"
tag = "zkube-Mint"
qualified_path = "zkube::models::index::mint"
manifest_name = "zkube-Mint-56f569fb"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "number"
type = "u32"
key = false

[[members]]
name = "expiration_timestamp"
type = "u64"
key = false
