kind = "DojoModel"
class_hash = "0x6b32bd4c06f4fd5b126544b3651bae8c241efe569e9be0429a4b9a7f135469a"
original_class_hash = "0x6b32bd4c06f4fd5b126544b3651bae8c241efe569e9be0429a4b9a7f135469a"
abi = "manifests/sepoliadev1/base/abis/models/zkube-Settings-161104df.json"
tag = "zkube-Settings"
qualified_path = "zkube::models::index::settings"
manifest_name = "zkube-Settings-161104df"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "is_set"
type = "bool"
key = false

[[members]]
name = "zkorp_address"
type = "felt252"
key = false

[[members]]
name = "daily_mode_price"
type = "u128"
key = false

[[members]]
name = "normal_mode_price"
type = "u128"
key = false
