kind = "DojoContract"
class_hash = "0x2328ceb195012d6e592d08eac067c0e1a6af5f96120cf19dbf38344551c35a8"
original_class_hash = "0x2328ceb195012d6e592d08eac067c0e1a6af5f96120cf19dbf38344551c35a8"
base_class_hash = "0x0"
abi = "manifests/sepoliadev1/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
