kind = "DojoContract"
class_hash = "0x88e90f3fc91e54174c1467ae2bf5a90d3f2a9459fc5f7e831c5bc5ca1107b9"
original_class_hash = "0x88e90f3fc91e54174c1467ae2bf5a90d3f2a9459fc5f7e831c5bc5ca1107b9"
base_class_hash = "0x0"
abi = "manifests/sepoliadev1/base/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-settings"
systems = [
    "update_zkorp_address",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"
