[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/sepoliadev1/deployment/abis/dojo-world.json"
address = "0x175a31288b8b364e77e76754b4fb6a57512c92df118e4e719825a0205fdd48c"
transaction_hash = "0x5ac0d841a8624bcf341300d321b8334b29cef31e9278999df634fed5055c4ab"
seed = "zKube4"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "sepoliadev1"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepoliadev1/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x1eef86abf147db4fd86788a44c4bae483d5352c75ca358880505f4417df8698"
class_hash = "0x11cc44b757f56fe33548f1a35ffad0f4ff8714b397d65d96fe1c494427cb2f2"
original_class_hash = "0x11cc44b757f56fe33548f1a35ffad0f4ff8714b397d65d96fe1c494427cb2f2"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepoliadev1/deployment/abis/contracts/zkube-account-6d28004d.json"
reads = []
writes = ["zkube-Player"]
init_calldata = []
tag = "zkube-account"
systems = [
    "create",
    "rename",
]
manifest_name = "zkube-account-6d28004d"

[[contracts]]
kind = "DojoContract"
address = "0x538532120f4ecf866371e874605c871ec4d42ba73795a8a06b8dc0f3bfd8cd8"
class_hash = "0x261fb0322818d856cda306ed7479874b965b9faead1b6485f1186449d9609f6"
original_class_hash = "0x261fb0322818d856cda306ed7479874b965b9faead1b6485f1186449d9609f6"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepoliadev1/deployment/abis/contracts/zkube-chest-5d3b3ea3.json"
reads = []
writes = [
    "zkube-Chest",
    "zkube-Participation",
]
init_calldata = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]
tag = "zkube-chest"
systems = [
    "claim",
    "sponsor",
    "sponsor_from",
]
manifest_name = "zkube-chest-5d3b3ea3"

[[contracts]]
kind = "DojoContract"
address = "0x5959f6ead1fdc97f9194c4f579256721bdfb19130b3105e992c5b6a99781f04"
class_hash = "0x567d3847c908c633484793b6cbd89d2809a91842aef41a73eda7fd7775ef413"
original_class_hash = "0x567d3847c908c633484793b6cbd89d2809a91842aef41a73eda7fd7775ef413"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepoliadev1/deployment/abis/contracts/zkube-minter-5ac6ce7d.json"
reads = []
writes = ["zkube-Mint"]
init_calldata = []
tag = "zkube-minter"
systems = [
    "mint",
    "claim_free_mint",
    "add_free_mint",
]
manifest_name = "zkube-minter-5ac6ce7d"

[[contracts]]
kind = "DojoContract"
address = "0x4197551d597ef9e912eb751b2b5e2185715211c86b5c90439f84f69b008670d"
class_hash = "0x2328ceb195012d6e592d08eac067c0e1a6af5f96120cf19dbf38344551c35a8"
original_class_hash = "0x2328ceb195012d6e592d08eac067c0e1a6af5f96120cf19dbf38344551c35a8"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepoliadev1/deployment/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = [
    "zkube-Player",
    "zkube-Game",
    "zkube-Tournament",
    "zkube-Settings",
    "zkube-Chest",
    "zkube-Participation",
]
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"

[[contracts]]
kind = "DojoContract"
address = "0x382a8b86a0039652b8e874123df592a81255878ebf9839b8c6aad618e60942c"
class_hash = "0x88e90f3fc91e54174c1467ae2bf5a90d3f2a9459fc5f7e831c5bc5ca1107b9"
original_class_hash = "0x88e90f3fc91e54174c1467ae2bf5a90d3f2a9459fc5f7e831c5bc5ca1107b9"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepoliadev1/deployment/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = [
    "zkube-Settings",
    "zkube-Admin",
]
init_calldata = ["0x0589d37adc1e5cf9ef58da510ee904aa9428d6e9a1c0d5c822392664d063796b"]
tag = "zkube-settings"
systems = [
    "update_zkorp_address",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"

[[contracts]]
kind = "DojoContract"
address = "0x59c1e7437369b46dc632188f3f410d9c4e0528949b7413a19b8ee34d89fc3ef"
class_hash = "0x7ece8a86dff2ae5211439a9b9815f1c33fddb124db613da204e63fc814ffab1"
original_class_hash = "0x7ece8a86dff2ae5211439a9b9815f1c33fddb124db613da204e63fc814ffab1"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepoliadev1/deployment/abis/contracts/zkube-tournament-2101600e.json"
reads = []
writes = ["zkube-Tournament"]
init_calldata = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]
tag = "zkube-tournament"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-tournament-2101600e"

[[contracts]]
kind = "DojoContract"
address = "0x3b5176779ab18ee76b6fb47f331d5840258e360eacdc3e49d3d9360e43c89ec"
class_hash = "0x12b37d078e6ee707b24a3d5e32684bdd0ca0d2afbc569a5b73175b489497115"
original_class_hash = "0x12b37d078e6ee707b24a3d5e32684bdd0ca0d2afbc569a5b73175b489497115"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepoliadev1/deployment/abis/contracts/zkube-zkorp-6cdc1046.json"
reads = []
writes = []
init_calldata = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]
tag = "zkube-zkorp"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-zkorp-6cdc1046"

[[models]]
kind = "DojoModel"
class_hash = "0x75ca4403fec8334e5819c3b134ab67420cf93d86b9809a7cfc2d2509530622f"
original_class_hash = "0x75ca4403fec8334e5819c3b134ab67420cf93d86b9809a7cfc2d2509530622f"
abi = "manifests/sepoliadev1/deployment/abis/models/zkube-Admin-3feb084f.json"
tag = "zkube-Admin"
qualified_path = "zkube::models::index::admin"
manifest_name = "zkube-Admin-3feb084f"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "is_set"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4ebc00a7ff8d99ef6a898161a20ce5f8e8a5cb96f471207a2b4d8a518262c0e"
original_class_hash = "0x4ebc00a7ff8d99ef6a898161a20ce5f8e8a5cb96f471207a2b4d8a518262c0e"
abi = "manifests/sepoliadev1/deployment/abis/models/zkube-Chest-4d11a491.json"
tag = "zkube-Chest"
qualified_path = "zkube::models::index::chest"
manifest_name = "zkube-Chest-4d11a491"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "point_target"
type = "u32"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false

[[models.members]]
name = "prize"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7df0095dee0c2eb9301e469f9f8268b4eadbd0c0c6ee21d29bee1cc6a35136f"
original_class_hash = "0x7df0095dee0c2eb9301e469f9f8268b4eadbd0c0c6ee21d29bee1cc6a35136f"
abi = "manifests/sepoliadev1/deployment/abis/models/zkube-Game-17e542e0.json"
tag = "zkube-Game"
qualified_path = "zkube::models::index::game"
manifest_name = "zkube-Game-17e542e0"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "moves"
type = "u32"
key = false

[[models.members]]
name = "next_row"
type = "u32"
key = false

[[models.members]]
name = "hammer_bonus"
type = "u8"
key = false

[[models.members]]
name = "wave_bonus"
type = "u8"
key = false

[[models.members]]
name = "totem_bonus"
type = "u8"
key = false

[[models.members]]
name = "hammer_used"
type = "u8"
key = false

[[models.members]]
name = "wave_used"
type = "u8"
key = false

[[models.members]]
name = "totem_used"
type = "u8"
key = false

[[models.members]]
name = "combo_counter"
type = "u8"
key = false

[[models.members]]
name = "max_combo"
type = "u8"
key = false

[[models.members]]
name = "blocks"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "mode"
type = "u8"
key = false

[[models.members]]
name = "start_time"
type = "u64"
key = false

[[models.members]]
name = "tournament_id"
type = "u64"
key = false

[[models.members]]
name = "score_in_tournament"
type = "u32"
key = false

[[models.members]]
name = "combo_counter_in_tournament"
type = "u8"
key = false

[[models.members]]
name = "max_combo_in_tournament"
type = "u8"
key = false

[[models.members]]
name = "pending_chest_prize"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x56861f7a7224ee70e86355af6c36f58a70919d519b945bf8715f5890e876e7d"
original_class_hash = "0x56861f7a7224ee70e86355af6c36f58a70919d519b945bf8715f5890e876e7d"
abi = "manifests/sepoliadev1/deployment/abis/models/zkube-Mint-56f569fb.json"
tag = "zkube-Mint"
qualified_path = "zkube::models::index::mint"
manifest_name = "zkube-Mint-56f569fb"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "number"
type = "u32"
key = false

[[models.members]]
name = "expiration_timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6d487a9e257063fa50bd2f6331ba3d8d82a62a4851b95802756a0b1b6f4a1de"
original_class_hash = "0x6d487a9e257063fa50bd2f6331ba3d8d82a62a4851b95802756a0b1b6f4a1de"
abi = "manifests/sepoliadev1/deployment/abis/models/zkube-Participation-7b168a64.json"
tag = "zkube-Participation"
qualified_path = "zkube::models::index::participation"
manifest_name = "zkube-Participation-7b168a64"

[[models.members]]
name = "chest_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "is_set"
type = "bool"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false

[[models.members]]
name = "claimed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1dc8b9f85a186d551a8d53b5b46cffe82a5505fa6855c0f9af7facb6946db09"
original_class_hash = "0x1dc8b9f85a186d551a8d53b5b46cffe82a5505fa6855c0f9af7facb6946db09"
abi = "manifests/sepoliadev1/deployment/abis/models/zkube-Player-a3c56d30.json"
tag = "zkube-Player"
qualified_path = "zkube::models::index::player"
manifest_name = "zkube-Player-a3c56d30"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false

[[models.members]]
name = "daily_streak"
type = "u8"
key = false

[[models.members]]
name = "last_active_day"
type = "u32"
key = false

[[models.members]]
name = "account_creation_day"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6b32bd4c06f4fd5b126544b3651bae8c241efe569e9be0429a4b9a7f135469a"
original_class_hash = "0x6b32bd4c06f4fd5b126544b3651bae8c241efe569e9be0429a4b9a7f135469a"
abi = "manifests/sepoliadev1/deployment/abis/models/zkube-Settings-161104df.json"
tag = "zkube-Settings"
qualified_path = "zkube::models::index::settings"
manifest_name = "zkube-Settings-161104df"

[[models.members]]
name = "id"
type = "u8"
key = true

[[models.members]]
name = "is_set"
type = "bool"
key = false

[[models.members]]
name = "zkorp_address"
type = "felt252"
key = false

[[models.members]]
name = "daily_mode_price"
type = "u128"
key = false

[[models.members]]
name = "normal_mode_price"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xd28fd534451aca076dda7a67fee4a48f120bb478b5b27be15879ac0037f6e5"
original_class_hash = "0xd28fd534451aca076dda7a67fee4a48f120bb478b5b27be15879ac0037f6e5"
abi = "manifests/sepoliadev1/deployment/abis/models/zkube-Tournament-120c37d1.json"
tag = "zkube-Tournament"
qualified_path = "zkube::models::index::tournament"
manifest_name = "zkube-Tournament-120c37d1"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "is_set"
type = "bool"
key = false

[[models.members]]
name = "prize"
type = "u128"
key = false

[[models.members]]
name = "top1_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top2_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top3_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top1_score"
type = "u32"
key = false

[[models.members]]
name = "top2_score"
type = "u32"
key = false

[[models.members]]
name = "top3_score"
type = "u32"
key = false

[[models.members]]
name = "top1_claimed"
type = "bool"
key = false

[[models.members]]
name = "top2_claimed"
type = "bool"
key = false

[[models.members]]
name = "top3_claimed"
type = "bool"
key = false

[[models.members]]
name = "top1_game_id"
type = "u32"
key = false

[[models.members]]
name = "top2_game_id"
type = "u32"
key = false

[[models.members]]
name = "top3_game_id"
type = "u32"
key = false
