kind = "DojoContract"
class_hash = "0x339870028bd52ad69b07c2d367b3f6308c62966cfa8db79ad6a3a8456301efe"
original_class_hash = "0x339870028bd52ad69b07c2d367b3f6308c62966cfa8db79ad6a3a8456301efe"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-settings"
systems = [
    "update_zkorp_address",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"
